name:                aoc-haskell
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/aoc-haskell#readme
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2023 Author name here
category:            Web
resolver: ghc-9.4.7
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - split
  - text
  - containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  aoc-haskell:
    source-dirs:      src
    main:             Main.hs
